// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6ZjIe-wk5-THGh60JJ3dC2MZezTEn-3Q',
    appId: '1:910389291409:web:f7a8ee7e3f83c42c7b5230',
    messagingSenderId: '910389291409',
    projectId: 'test-d5ce8',
    authDomain: 'test-d5ce8.firebaseapp.com',
    storageBucket: 'test-d5ce8.appspot.com',
    measurementId: 'G-9D3M5VDCNF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBShzj-yeLzFKaH6P2Ve0ZpgJ_m6xJWfUo',
    appId: '1:910389291409:android:9023249b4d55217a7b5230',
    messagingSenderId: '910389291409',
    projectId: 'test-d5ce8',
    storageBucket: 'test-d5ce8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKMcpNTv_oSOCGG_OOcG2yQKqsvfoWkKk',
    appId: '1:910389291409:ios:a65255f7fc6d5ce17b5230',
    messagingSenderId: '910389291409',
    projectId: 'test-d5ce8',
    storageBucket: 'test-d5ce8.appspot.com',
    iosBundleId: 'com.example.flutterProjectBtl',
  );
}
