// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgoB-hO1dPQpZYsvJPfNSYuqnzOqUjkwo',
    appId: '1:664868004212:web:011528d92c3e30459f0c21',
    messagingSenderId: '664868004212',
    projectId: 'testlogin-4bbfd',
    authDomain: 'testlogin-4bbfd.firebaseapp.com',
    storageBucket: 'testlogin-4bbfd.appspot.com',
    measurementId: 'G-PG392TJ5FF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAcqL2jlimB1A-OyOo3NkhmqaNBva3VmM',
    appId: '1:664868004212:android:a700ea2098a8b55b9f0c21',
    messagingSenderId: '664868004212',
    projectId: 'testlogin-4bbfd',
    storageBucket: 'testlogin-4bbfd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtQ2CzeAzOcRsdamwKRNyUwgA4B64BMEU',
    appId: '1:664868004212:ios:d3dd7aadba5f4f6b9f0c21',
    messagingSenderId: '664868004212',
    projectId: 'testlogin-4bbfd',
    storageBucket: 'testlogin-4bbfd.appspot.com',
    iosBundleId: 'com.example.flutterProjectBtl',
  );
}
